# Generated by Django 4.1.13 on 2024-11-18 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_traded_quantity', models.IntegerField(blank=True, null=True)),
                ('lower_circuit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('upper_circuit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('multiplier', models.IntegerField(blank=True, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('total_traded_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_buy_quantity', models.BigIntegerField(blank=True, null=True)),
                ('total_sell_quantity', models.BigIntegerField(blank=True, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buy_quantity', models.BigIntegerField(blank=True, null=True)),
                ('instrument_token', models.CharField(max_length=20)),
                ('exchange_segment', models.CharField(max_length=10)),
                ('trading_symbol', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=20)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_type', models.CharField(choices=[('index', 'Index'), ('equity', 'Equity'), ('futures', 'Futures'), ('calloptions', 'Call Options'), ('putoptions', 'Put Options')], default='equity', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('prev_day_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_traded_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
