# Generated by Django 4.1.13 on 2024-11-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='display_symbol',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holding',
            name='scrip_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
